DROP INDEX HALF_TRADE_Q0_IDX;

CREATE INDEX HALF_TRADE_Q0_IDX ON HALF_TRADE 
(TRADE_STATUS, ORIGINATOR_FIRM, TRADING_DAY, EXCHANGE_CODE) 
LOCAL 
TABLESPACE INDX;

DROP INDEX HALF_TRADE_Q1_IDX;
  
CREATE INDEX HALF_TRADE_Q1_IDX ON HALF_TRADE 
(ORIGINATOR_FIRM, TRADE_STATUS, TRADING_DAY, EXCHANGE_CODE, LOGICAL_COMMODITY) 
LOCAL
TABLESPACE INDX;
