--HEARTBEAT -

update heartbeat set startup_timestamp = sysdate; !check with development on default values.....

alter table heartbeat modify startup_timestamp not null;

alter table heartbeat rename to heartbeat_bkp;

create table heartbeat
    as
select SOURCE, COMPONENT_NAME, STARTUP_TIMESTAMP, PERIOD, LAST_HEARTBEAT, EVENT_INTERFACE, EVENT_PORT, EVENT_MNEMONIC_LIST
  from heartbeat_bkp;

DROP INDEX HEARTBEAT_PK_IDX;

CREATE UNIQUE INDEX HEARTBEAT_PK_IDX
    ON HEARTBEAT(SOURCE,COMPONENT_NAME)
TABLESPACE INDX;

Drop table heartbeat_bkp;


--MESSAGE_AUDIT_RESULT -

alter table message_audit_results rename to message_audit_results_bkp;

Table altered.


create table message_audit_results
    as select QUERY_ID, QUERY_ROW_NUM, TRADING_DAY, EXCHANGE_CODE, OUTPUT_SEQUENCE_NO,
   MESSAGE_ID, TRANSACTION_ID, EXTERNAL_IND, MESSAGE_SRC, CLASS, FIRM, SERIES_PARTITION_KEY,
   MESSAGE_TYPE, SLIP_ID, MESSAGE_DATA_VERSION, CREATION_DAY, ACTION_FLAG, MESSAGE_DATA
    from message_audit_results_bkp;

drop index MSG_ADT_RSLT_PK_IDX;

Index dropped.

CREATE UNIQUE INDEX MSG_ADT_RSLT_PK_IDX
    ON MESSAGE_AUDIT_RESULTS(QUERY_ID,QUERY_ROW_NUM)
TABLESPACE INDX;


drop table MESSAGE_AUDIT_RESULTS_BKP;

purge recyclebin;

--PKA_RESULTS -

update pka_results set LONG_BF_CORRECTED_VOL = 0, SHORT_BF_CORRECTED_VOL = 0;

alter table pka_results modify LONG_BF_CORRECTED_VOL number not null;

Table altered.

alter table pka_results modify SHORT_BF_CORRECTED_VOL number not null;

Table altered.

alter table pka_results add NOTICE_EXPIRY_DAY_TMP number;

Table altered.

SQL> update pka_results set NOTICE_EXPIRY_DAY_TMP = NOTICE_EXPIRY_DAY;

13625 rows updated.

SQL> alter table pka_results modify NOTICE_EXPIRY_DAY_TMP  number not null;

Table altered.

SQL> alter table pka_results drop column NOTICE_EXPIRY_DAY;

Table altered.

SQL>  alter table pka_results rename column NOTICE_EXPIRY_DAY_TMP to NOTICE_EXPIRY_DAY;

Table altered.

SQL>



ALTER TABLE commodity_contract
ADD
( deadline_group                       VARCHAR2(10)
, system_mode_group                    VARCHAR2(5)
);

UPDATE commodity_contract
SET system_mode_group = CASE RTRIM(physical_commodity) WHEN 'TPI' THEN 'TSE' WHEN 'J' THEN 'TIFFE' ELSE 'DEF' END;

COMMIT;

ALTER TABLE commodity_contract
MODIFY
( system_mode_group                    CONSTRAINT cmdty_cnt_system_mode_group_nn NOT NULL
);

COMMENT ON COLUMN commodity_contract.system_mode_group IS'
The system mode group will be used to lookup the current system mode for a commodity.
The expected values differ by exchange code and may be further extended via LDS.
L - DEFAULT, TIFFE or TSE
O - DEFAULT
X - DEFAULT
';


ALTER TABLE TRIDPERF3.COMMODITY_CONTRACT MODIFY(NORMAL_NOTICE_DEADLINE NULL)
/
ALTER TABLE TRIDPERF3.COMMODITY_CONTRACT MODIFY(NOTICE_PERIOD_DEADLINE NULL)
/
ALTER TABLE TRIDPERF3.COMMODITY_CONTRACT MODIFY(NOTICE_EXPIRY_DEADLINE NULL)
/
ALTER TABLE TRIDPERF3.COMMODITY_CONTRACT MODIFY(NORMAL_CPS_TIME NULL)
/
ALTER TABLE TRIDPERF3.COMMODITY_CONTRACT MODIFY(NOTICE_PERIOD_CPS_TIME NULL)
/
ALTER TABLE TRIDPERF3.COMMODITY_CONTRACT MODIFY(EXPIRY_CPS_TIME NULL)
/


ALTER TABLE TRIDPERF3.MESSAGE_AUDIT
    DROP CONSTRAINT TSCS_AUDIT_PK
/
DROP INDEX TRIDPERF3.MESSAGE_AUDIT_Q2_IDX
/
DROP INDEX TRIDPERF3.MESSAGE_AUDIT_Q1_IDX
/
DROP INDEX TRIDPERF3.MESSAGE_AUDIT_Q0_IDX
/
DROP INDEX TRIDPERF3.MESSAGE_AUDIT_PK_IDX
/
ALTER TABLE TRIDPERF3.MESSAGE_AUDIT
    DROP CONSTRAINT TSCS_ADT_TRADING_DAY_NN
/
ALTER TABLE TRIDPERF3.MESSAGE_AUDIT
    DROP CONSTRAINT TSCS_ADT_SERIES_PART_KEY_NN
/
ALTER TABLE TRIDPERF3.MESSAGE_AUDIT
    DROP CONSTRAINT TSCS_ADT_OUTPUT_SEQ_NO_NN
/
ALTER TABLE TRIDPERF3.MESSAGE_AUDIT
    DROP CONSTRAINT TSCS_ADT_MESSAGE_TYPE_NN
/
ALTER TABLE TRIDPERF3.MESSAGE_AUDIT
    DROP CONSTRAINT TSCS_ADT_MESSAGE_SRC_NN
/
ALTER TABLE TRIDPERF3.MESSAGE_AUDIT
    DROP CONSTRAINT TSCS_ADT_MESSAGE_ID_NN
/
ALTER TABLE TRIDPERF3.MESSAGE_AUDIT
    DROP CONSTRAINT TSCS_ADT_FIRM_NN
/
ALTER TABLE TRIDPERF3.MESSAGE_AUDIT
    DROP CONSTRAINT TSCS_ADT_EXTERNAL_IND_NN
/
ALTER TABLE TRIDPERF3.MESSAGE_AUDIT
    DROP CONSTRAINT TSCS_ADT_EXCHANGE_CODE_NN
/
ALTER TABLE TRIDPERF3.MESSAGE_AUDIT
    DROP CONSTRAINT TSCS_ADT_CLASS_NN
/
ALTER TABLE TRIDPERF3.MESSAGE_AUDIT RENAME TO MESSAGE_AUDIT_CAD57717
/
CREATE TABLE TRIDPERF3.MESSAGE_AUDIT
(
    TRADING_DAY          NUMBER(6,0)  NOT NULL,
    EXCHANGE_CODE        VARCHAR2(5)  NOT NULL,
    OUTPUT_SEQUENCE_NO   NUMBER       NOT NULL,
    MESSAGE_ID           NUMBER       NOT NULL,
    TRANSACTION_ID       NUMBER(38,0) DEFAULT 0 NOT NULL,
    EXTERNAL_IND         VARCHAR2(1)  NOT NULL,
    MESSAGE_SRC          VARCHAR2(20) NOT NULL,
    CLASS                VARCHAR2(11) NOT NULL,
    FIRM                 VARCHAR2(5)  NOT NULL,
    SERIES_PARTITION_KEY NUMBER(20,0) NOT NULL,
    MESSAGE_TYPE         VARCHAR2(10) NOT NULL,
    SLIP_ID              NUMBER           NULL,
    MESSAGE_DATA_VERSION VARCHAR2(5)      NULL,
    CREATION_DAY         NUMBER(6,0)      NULL,
    ACTION_FLAG          VARCHAR2(1)      NULL,
    MESSAGE_DATA         BLOB             NULL
)
ORGANIZATION HEAP
LOB(MESSAGE_DATA) STORE AS TSCS_AUDIT_LOB_STORE1
TABLESPACE APP
PCTFREE 10
PCTUSED 0
INITRANS 1
MAXTRANS 255
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCACHE
NOROWDEPENDENCIES
PARTITION BY RANGE(TRADING_DAY)
INTERVAL (1)
(PARTITION P_TRDNG_DY_DFLT VALUES LESS THAN (1)
    TABLESPACE APP
   )
/
COMMENT ON TABLE TRIDPERF3.MESSAGE_AUDIT IS
'
This table holds a record for every transaction message completed by the system.
The audit messages form a complete history of half_trade, notification and audit transactions,
plus any system event records that are processed.
The complete message is held in the BLOB field.
The other fields are then used to locate the appropriate messages during search or query operations.
'
/
COMMENT ON COLUMN TRIDPERF3.MESSAGE_AUDIT.MESSAGE_SRC IS
'
This field identifies the source of the audit message within Trident.
Audit messages maybe derived directly fro TRS (Tramp) messages or generated by internal processing with Trident.
This column can take the following values:
     AUDIT_REPLICATOR - Audit record generated during processing of Tramp message which is neither a Trade nor a Note.
     NOTE_REPLICATOR  - Audit record generated during processing of a Note Submission (V111) Tramp message.
     TRADE_REPLICATOR - Audit record generated during processing of a Trade Submission (V058) Tramp message.
'
/
COMMENT ON COLUMN TRIDPERF3.MESSAGE_AUDIT.CLASS IS
'
This field identifies the message class of the data held within the BLOB.
The value will be dependant on the message_src and the data defined within the originating Tramp message.
For AUDIT_REPLICATOR the following values may be used:
     CLEARING
     COMMON
     OLD_TRAMP
     PRICE
For NOTE_REPLICATOR the values are:
     CLEARING
     GHOST_NOTE
     OLD_TRAMP
For TRADE_REPLICATOR the values are:
     GHOST_KERB
     GHOST_TRADE
     KERB
     TRADE
'
/
ALTER SESSION ENABLE PARALLEL DML
/
INSERT INTO TRIDPERF3.MESSAGE_AUDIT
( TRADING_DAY,
  EXCHANGE_CODE,
  OUTPUT_SEQUENCE_NO,
  MESSAGE_ID,
  TRANSACTION_ID,
  EXTERNAL_IND,
  MESSAGE_SRC,
  CLASS,
  FIRM,
  SERIES_PARTITION_KEY,
  MESSAGE_TYPE,
  SLIP_ID,
  MESSAGE_DATA_VERSION,
  CREATION_DAY,
  ACTION_FLAG,
  MESSAGE_DATA ) 
SELECT
TRADING_DAY,
EXCHANGE_CODE,
OUTPUT_SEQUENCE_NO,
MESSAGE_ID,
TRANSACTION_ID,
EXTERNAL_IND,
MESSAGE_SRC,
CLASS,
FIRM,
SERIES_PARTITION_KEY,
MESSAGE_TYPE,
SLIP_ID,
MESSAGE_DATA_VERSION,
CREATION_DAY,
ACTION_FLAG,
MESSAGE_DATA
FROM TRIDPERF3.MESSAGE_AUDIT_CAD57717
/
COMMIT
/
ALTER TABLE TRIDPERF3.MESSAGE_AUDIT
    ADD CONSTRAINT TSCS_ADT_CLASS_NN
    CHECK ("CLASS" IS NOT NULL)
/
ALTER TABLE TRIDPERF3.MESSAGE_AUDIT
    ADD CONSTRAINT TSCS_ADT_EXCHANGE_CODE_NN
    CHECK ("EXCHANGE_CODE" IS NOT NULL)
/
ALTER TABLE TRIDPERF3.MESSAGE_AUDIT
    ADD CONSTRAINT TSCS_ADT_EXTERNAL_IND_NN
    CHECK ("EXTERNAL_IND" IS NOT NULL)
/
ALTER TABLE TRIDPERF3.MESSAGE_AUDIT
    ADD CONSTRAINT TSCS_ADT_FIRM_NN
    CHECK ("FIRM" IS NOT NULL)
/
ALTER TABLE TRIDPERF3.MESSAGE_AUDIT
    ADD CONSTRAINT TSCS_ADT_MESSAGE_ID_NN
    CHECK ("MESSAGE_ID" IS NOT NULL)
/
ALTER TABLE TRIDPERF3.MESSAGE_AUDIT
    ADD CONSTRAINT TSCS_ADT_MESSAGE_SRC_NN
    CHECK ("MESSAGE_SRC" IS NOT NULL)
/
ALTER TABLE TRIDPERF3.MESSAGE_AUDIT
    ADD CONSTRAINT TSCS_ADT_MESSAGE_TYPE_NN
    CHECK ("MESSAGE_TYPE" IS NOT NULL)
/
ALTER TABLE TRIDPERF3.MESSAGE_AUDIT
    ADD CONSTRAINT TSCS_ADT_OUTPUT_SEQ_NO_NN
    CHECK ("OUTPUT_SEQUENCE_NO" IS NOT NULL)
/
ALTER TABLE TRIDPERF3.MESSAGE_AUDIT
    ADD CONSTRAINT TSCS_ADT_SERIES_PART_KEY_NN
    CHECK ("SERIES_PARTITION_KEY" IS NOT NULL)
/
ALTER TABLE TRIDPERF3.MESSAGE_AUDIT
    ADD CONSTRAINT TSCS_ADT_TRADING_DAY_NN
    CHECK ("TRADING_DAY" IS NOT NULL)
/



CREATE UNIQUE INDEX TRIDPERF3.MESSAGE_AUDIT_PK_IDX
    ON TRIDPERF3.MESSAGE_AUDIT(TRADING_DAY,EXCHANGE_CODE,OUTPUT_SEQUENCE_NO)
TABLESPACE INDX
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
LOCAL
(PARTITION P_TRDNG_DY_DFLT 
    TABLESPACE INDX
    PCTFREE 10
    INITRANS 2
    MAXTRANS 255
    STORAGE(INITIAL 64K)
    LOGGING,
            PARTITION SYS_P125530 
    TABLESPACE INDX
    PCTFREE 10
    INITRANS 2
    MAXTRANS 255
    STORAGE(INITIAL 64K)
    LOGGING,
            PARTITION SYS_P125533 
    TABLESPACE INDX
    PCTFREE 10
    INITRANS 2
    MAXTRANS 255
    STORAGE(INITIAL 64K)
    LOGGING,
            PARTITION SYS_P125536 
    TABLESPACE INDX
    PCTFREE 10
    INITRANS 2
    MAXTRANS 255
    STORAGE(INITIAL 64K)
    LOGGING,
            PARTITION SYS_P125539 
    TABLESPACE INDX
    PCTFREE 10
    INITRANS 2
    MAXTRANS 255
    STORAGE(INITIAL 64K)
    LOGGING,
            PARTITION SYS_P125542 
    TABLESPACE INDX
    PCTFREE 10
    INITRANS 2
    MAXTRANS 255
    STORAGE(INITIAL 64K)
    LOGGING,
            PARTITION SYS_P125545 
    TABLESPACE INDX
    PCTFREE 10
    INITRANS 2
    MAXTRANS 255
    STORAGE(INITIAL 64K)
    LOGGING)
NOCOMPRESS
/
CREATE INDEX TRIDPERF3.MESSAGE_AUDIT_Q0_IDX
    ON TRIDPERF3.MESSAGE_AUDIT(EXCHANGE_CODE,FIRM)
TABLESPACE INDX
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
LOCAL
(PARTITION P_TRDNG_DY_DFLT 
    TABLESPACE INDX
    PCTFREE 10
    INITRANS 2
    MAXTRANS 255
    STORAGE(INITIAL 64K)
    LOGGING,
            PARTITION SYS_P125530 
    TABLESPACE INDX
    PCTFREE 10
    INITRANS 2
    MAXTRANS 255
    STORAGE(INITIAL 64K)
    LOGGING,
            PARTITION SYS_P125533 
    TABLESPACE INDX
    PCTFREE 10
    INITRANS 2
    MAXTRANS 255
    STORAGE(INITIAL 64K)
    LOGGING,
            PARTITION SYS_P125536 
    TABLESPACE INDX
    PCTFREE 10
    INITRANS 2
    MAXTRANS 255
    STORAGE(INITIAL 64K)
    LOGGING,
            PARTITION SYS_P125539 
    TABLESPACE INDX
    PCTFREE 10
    INITRANS 2
    MAXTRANS 255
    STORAGE(INITIAL 64K)
    LOGGING,
            PARTITION SYS_P125542 
    TABLESPACE INDX
    PCTFREE 10
    INITRANS 2
    MAXTRANS 255
    STORAGE(INITIAL 64K)
    LOGGING,
            PARTITION SYS_P125545 
    TABLESPACE INDX
    PCTFREE 10
    INITRANS 2
    MAXTRANS 255
    STORAGE(INITIAL 64K)
    LOGGING)
NOCOMPRESS
/
CREATE INDEX TRIDPERF3.MESSAGE_AUDIT_Q1_IDX
    ON TRIDPERF3.MESSAGE_AUDIT(EXCHANGE_CODE,SLIP_ID,MESSAGE_TYPE)
TABLESPACE INDX
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
LOCAL
(PARTITION P_TRDNG_DY_DFLT 
    TABLESPACE INDX
    PCTFREE 10
    INITRANS 2
    MAXTRANS 255
    STORAGE(INITIAL 64K)
    LOGGING,
            PARTITION SYS_P125530 
    TABLESPACE INDX
    PCTFREE 10
    INITRANS 2
    MAXTRANS 255
    STORAGE(INITIAL 64K)
    LOGGING,
            PARTITION SYS_P125533 
    TABLESPACE INDX
    PCTFREE 10
    INITRANS 2
    MAXTRANS 255
    STORAGE(INITIAL 64K)
    LOGGING,
            PARTITION SYS_P125536 
    TABLESPACE INDX
    PCTFREE 10
    INITRANS 2
    MAXTRANS 255
    STORAGE(INITIAL 64K)
    LOGGING,
            PARTITION SYS_P125539 
    TABLESPACE INDX
    PCTFREE 10
    INITRANS 2
    MAXTRANS 255
    STORAGE(INITIAL 64K)
    LOGGING,
            PARTITION SYS_P125542 
    TABLESPACE INDX
    PCTFREE 10
    INITRANS 2
    MAXTRANS 255
    STORAGE(INITIAL 64K)
    LOGGING,
            PARTITION SYS_P125545 
    TABLESPACE INDX
    PCTFREE 10
    INITRANS 2
    MAXTRANS 255
    STORAGE(INITIAL 64K)
    LOGGING)
NOCOMPRESS
/
CREATE INDEX TRIDPERF3.MESSAGE_AUDIT_Q2_IDX
    ON TRIDPERF3.MESSAGE_AUDIT(TRANSACTION_ID)
TABLESPACE INDX
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
LOCAL
(PARTITION P_TRDNG_DY_DFLT 
    TABLESPACE INDX
    PCTFREE 10
    INITRANS 2
    MAXTRANS 255
    STORAGE(INITIAL 64K)
    LOGGING,
            PARTITION SYS_P125530 
    TABLESPACE INDX
    PCTFREE 10
    INITRANS 2
    MAXTRANS 255
    STORAGE(INITIAL 64K)
    LOGGING,
            PARTITION SYS_P125533 
    TABLESPACE INDX
    PCTFREE 10
    INITRANS 2
    MAXTRANS 255
    STORAGE(INITIAL 64K)
    LOGGING,
            PARTITION SYS_P125536 
    TABLESPACE INDX
    PCTFREE 10
    INITRANS 2
    MAXTRANS 255
    STORAGE(INITIAL 64K)
    LOGGING,
            PARTITION SYS_P125539 
    TABLESPACE INDX
    PCTFREE 10
    INITRANS 2
    MAXTRANS 255
    STORAGE(INITIAL 64K)
    LOGGING,
            PARTITION SYS_P125542 
    TABLESPACE INDX
    PCTFREE 10
    INITRANS 2
    MAXTRANS 255
    STORAGE(INITIAL 64K)
    LOGGING,
            PARTITION SYS_P125545 
    TABLESPACE INDX
    PCTFREE 10
    INITRANS 2
    MAXTRANS 255
    STORAGE(INITIAL 64K)
    LOGGING)
NOCOMPRESS
/
ALTER TABLE TRIDPERF3.MESSAGE_AUDIT
    ADD CONSTRAINT TSCS_AUDIT_PK
    PRIMARY KEY (TRADING_DAY,EXCHANGE_CODE,OUTPUT_SEQUENCE_NO)
    DISABLE
    NOVALIDATE
/
